# Generated by Django 5.0.4 on 2024-05-09 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_messagemodel_id'),
        ('properties', '0002_alter_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='properties.property'),
        ),
    ]
